# -*- coding: utf-8 -*-
"""AI2THORgeneratepatches.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXJ_xA1XH-y_sql-jF6bCfUflPSmTQZA
"""

import random
import matplotlib.path as mplPath
import collections
import numpy as np
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection
import matplotlib.pyplot as plt
from matplotlib import pylab
import shapely.geometry

"""# generate patches"""

def generate_patches(cx, cy, filename):
    
    plt.figure(figsize=(8, 6), dpi=80)
    ax=pylab.gca()
    ax.set_xlim(-2,  cx)
    ax.set_ylim(-2,  cy)
    ax.set_ylim(ax.get_ylim()[::-1])


    polygon = np.asarray(np.load(filename, allow_pickle= True))

    patches = []
    for i in range(polygon.shape[0]):
        obj = Polygon(polygon[i], True)
        patches.append(obj)


    p = PatchCollection(patches, alpha=1)
    p.set_facecolor(c='none')
    p.set_edgecolor(c='#9370DB')
    p.set_lw(2)

    ax.add_collection(p)
    ax.set_aspect('equal')
    
